#Sesso:
#0 -> Uomo
#1-> Donna

#Barba:
#true -> Si
#false -> No

#Baffi:
#true -> Si
#false -> No

#Capelli:
#0 -> Calvo
#1 -> Lisci
#2 -> Mossi
#3 -> Ricci

#Colore Capelli:
#0 -> Bianchi
#1 -> Biondi
#2 -> Rossi
#3 -> Marroni
#4 -> Neri

#Colore Occhi:
#0 -> Azzurri
#1 -> Marroni
#2 -> Neri

#Cappello:
#true -> Si
#false -> No

#Occhiali
#true -> Si
#false -> No

Personaggi:
  mostra_nome: true #Mostra il nome sotto a ogni foto
  1:
    nome: 'Alfred'
    sesso: 0
    barba: false
    baffi: true
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 2
    colore_occhi: 2
    foto: 'resources/img/1.jpg'

  2:
    nome: 'Anita'
    sesso: 1
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 1
    colore_occhi: 2
    foto: 'resources/img/2.jpg'

  3:
    nome: 'Anne'
    sesso: 1
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 3
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/3.jpg'

  4:
    nome: 'Bernard'
    sesso: 0
    barba: false
    baffi: false
    cappello: true
    occhiali: false
    capelli: 1
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/4.jpg'

  5:
    nome: 'Bill'
    sesso: 0
    barba: true
    baffi: false
    cappello: false
    occhiali: false
    capelli: 0
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/5.jpg'

  6:
    nome: 'Charles'
    sesso: 0
    barba: false
    baffi: true
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 1
    colore_occhi: 2
    foto: 'resources/img/6.jpg'

  7:
    nome: 'Claire'
    sesso: 1
    barba: false
    baffi: false
    cappello: true
    occhiali: true
    capelli: 1
    colore_capelli: 1
    colore_occhi: 1
    foto: 'resources/img/7.jpg'

  8:
    nome: 'David'
    sesso: 0
    barba: true
    baffi: false
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/8.jpg'

  9:
    nome: 'Eric'
    sesso: 0
    barba: false
    baffi: false
    cappello: true
    occhiali: false
    capelli: 1
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/9.jpg'

  10:
    nome: 'Frans'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 3
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/10.jpg'

  11:
    nome: 'George'
    sesso: 0
    barba: false
    baffi: false
    cappello: true
    occhiali: false
    capelli: 1
    colore_capelli: 0
    colore_occhi: 1
    foto: 'resources/img/11.jpg'

  12:
    nome: 'Herman'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 0
    colore_capelli: 2
    colore_occhi: 2
    foto: 'resources/img/12.jpg'

  13:
    nome: 'Joe'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: true
    capelli: 3
    colore_capelli: 1
    colore_occhi: 2
    foto: 'resources/img/13.jpg'

  14:
    nome: 'Maria'
    sesso: 1
    barba: false
    baffi: false
    cappello: true
    occhiali: false
    capelli: 2
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/14.jpg'

  15:
    nome: 'Max'
    sesso: 0
    barba: false
    baffi: true
    cappello: false
    occhiali: false
    capelli: 3
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/15.jpg'

  16:
    nome: 'Paul'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: true
    capelli: 2
    colore_capelli: 0
    colore_occhi: 2
    foto: 'resources/img/16.jpg'

  17:
    nome: 'Peter'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 0
    colore_occhi: 2
    foto: 'resources/img/17.jpg'

  18:
    nome: 'Philip'
    sesso: 0
    barba: true
    baffi: false
    cappello: false
    occhiali: false
    capelli: 3
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/18.jpg'

  19:
    nome: 'Richard'
    sesso: 0
    barba: true
    baffi: true
    cappello: false
    occhiali: false
    capelli: 0
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/19.jpg'

  20:
    nome: 'Robert'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/20.jpg'

  21:
    nome: 'Sam'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 0
    colore_capelli: 0
    colore_occhi: 2
    foto: 'resources/img/21.jpg'






