#Sesso:
#0 -> Uomo
#1-> Donna

#Barba:
#true -> Si
#false -> No

#Baffi:
#true -> Si
#false -> No

#Capelli:
#0 -> Calvo
#1 -> Lisci
#2 -> Mossi
#3 -> Ricci

#Colore Capelli:
#0 -> Bianchi
#1 -> Biondi
#2 -> Rossi
#3 -> Marroni
#4 -> Neri

#Colore Occhi:
#0 -> Azzurri
#1 -> Marroni
#2 -> Neri

#Cappello:
#true -> Si
#false -> No

#Occhiali
#true -> Si
#false -> No

Personaggi:
  mostra_nome: true #Mostra il nome sotto a ogni foto
  1:
    nome: 'Amendola'
    sesso: 0
    barba: true
    baffi: true
    cappello: false
    occhiali: true
    capelli: 1
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/amendola.png'

  2:
    nome: 'Battimelli'
    sesso: 0
    barba: true
    baffi: true
    cappello: false
    occhiali: false
    capelli: 2
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/battimelli.png'

  3:
    nome: 'Paciello'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: true
    capelli: 2
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/paciello.png'

  4:
    nome: 'Musella'
    sesso: 0
    barba: true
    baffi: true
    cappello: false
    occhiali: false
    capelli: 2
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/musella.png'

  5:
    nome: 'Chiaramonte'
    sesso: 0
    barba: true
    baffi: true
    cappello: false
    occhiali: true
    capelli: 1
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/chiaramonte.png'

  6:
    nome: 'Russo'
    sesso: 0
    barba: true
    baffi: false
    cappello: false
    occhiali: true
    capelli: 2
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/russo.png'

  7:
    nome: 'Langellotti'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 1
    colore_capelli: 1
    colore_occhi: 1
    foto: 'resources/img/langellotti.png'

  8:
    nome: 'Pontecorvo'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: false
    capelli: 2
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/pontecorvo.png'

  9:
    nome: 'Dapice'
    sesso: 0
    barba: false
    baffi: false
    cappello: false
    occhiali: true
    capelli: 2
    colore_capelli: 3
    colore_occhi: 2
    foto: 'resources/img/dapice.png'

  10:
    nome: 'Chiaramonte'
    sesso: 0
    barba: true
    baffi: true
    cappello: false
    occhiali: true
    capelli: 1
    colore_capelli: 4
    colore_occhi: 2
    foto: 'resources/img/musella.png'






